catalog/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),  # Trang chủ của app "catalog"
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path(
        'mybooks/',
        views.LoanedBooksByUserListView.as_view(),
        name='my-borrowed',
    ),
    path(
        'borrowed/',
        views.LoanedBooksAllListView.as_view(),
        name='all-borrowed'),
    path(
        'book/<uuid:pk>/return/',
        views.mark_book_returned,
        name='mark-returned',
    ),
    path(
        'book/<uuid:pk>/renew/',
        views.renew_book_librarian,
        name='renew-book-librarian'
    ),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/',
         views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/',
         views.AuthorDelete.as_view(), name='author-delete'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path(
        'author/<int:pk>',
        views.AuthorDetailView.as_view(),
        name='author-detail'
    ),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid  # for unique BookInstance IDs
from . import constants  # constants file
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from datetime import date


class Genre(models.Model):

    """Model representing a book genre."""
    name = models.CharField(
        max_length=constants.MAX_LENGTH_GENRE_NAME,
        help_text=_('Enter a book genre (e.g. Science Fiction)'))

    def __str__(self):
        return self.name  # Lấy tên thể loại của sách


class Book(models.Model):

    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=constants.MAX_LENGTH_TITLE)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(
        max_length=constants.MAX_LENGTH_SUMMARY,
        help_text=_('Enter a brief description of the book'))
    isbn = models.CharField(
        _('ISBN'),
        max_length=constants.MAX_LENGTH_ISBN,
        unique=True,
        help_text=(_('13 Character '
                   '<a href="https://www.isbn-international.org/content/'
                     'what-isbn">ISBN number</a>'))
    )  # Mã số của sách, unique
    genre = models.ManyToManyField(
        Genre,
        help_text=_('Select a genre for this book'))  # Book 0..* 1..* Genre

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # id ngầm autofield, tăng tự động.
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for Genre.
        This is required to display genre is Admin."""
        return ','.join(genre.name for genre in self.genre.all()[:3])
    display_genre.short_description = _('Genre')


class BookInstance(models.Model):

    """Model representing a specific copy of a book
    (i.e. that can be borrowed from the library).
    Bản sao cụ thể của một cuốn sách (ví dụ: có thể mượn)."""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text=_('Unique ID for this book across whole library'))
    book = models.ForeignKey('Book', on_delete=models.RESTRICT)
    imprint = models.CharField(max_length=constants.MAX_LENGTH_IMPRINT)
    due_back = models.DateField(null=True, blank=True)

    status = models.CharField(
        max_length=1,
        choices=constants.LOAN_STATUS,
        blank=True,
        default=constants.LOAN_STATUS_MAINTENANCE,
        help_text=_('Book availability'),
    )

    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        return self.due_back and date.today() > self.due_back

    class Meta:
        # Sắp xếp theo hạn trả
        ordering = ['due_back']
        permissions = (
            ("can_mark_returned", "Set book as returned"),
        )

    def __str__(self):
        return f'{self.id} ({self.book.title})'


class Author(models.Model):

    """Model representing an author."""
    first_name = models.CharField(max_length=constants.MAX_LENGTH_AUTHOR_NAME)
    last_name = models.CharField(max_length=constants.MAX_LENGTH_AUTHOR_NAME)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(_('Died'), null=True, blank=True)

    class Meta:
        # Sắp xếp theo tên
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from catalog import constants


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text=_("Enter a date between now and 4 weeks (default 3).")
    )

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today)
        if (data > datetime.date.today() +
                datetime.timedelta(weeks=constants.MAX_RENEWAL_WEEKS)):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        return data


catalog/views.py
from django.views import generic
from .models import Book
from django.shortcuts import render
from django.utils.translation import gettext as _
from catalog.models import Book, Author, BookInstance, Genre
from catalog.forms import RenewBookForm
from catalog import constants
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


@login_required
def index(request):
    """View function for home page of site."""

    # Đếm số lượng bản ghi trong các bảng
    num_books = Book.objects.count()
    num_instances = BookInstance.objects.count()

    # Đếm số lượng sách còn sẵn sàng mượn (status = available)
    num_instances_available = BookInstance.objects.filter(
        status__exact=constants.LOAN_STATUS_AVAILABLE).count()

    num_authors = Author.objects.count()

    # Lấy số lượt truy cập từ session (mặc định là 1)
    num_visits = request.session.get('num_visits', 1)

    # Cập nhật giá trị đó và lưu lại
    request.session['num_visits'] = num_visits + 1

    # Dữ liệu truyền vào template
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    # Trả về template đã render
    return render(request, 'index.html', context=context)


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    paginate_by = constants.BOOK_LIST_VIEW_PAGINATE
    context_object_name = 'book_list'  # trùng với template mặc định
    template_name = 'catalog/book_list.html'


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = self.get_object()
        context['copies'] = book.bookinstance_set.all()
        context['STATUS_AVAILABLE'] = constants.LOAN_STATUS_AVAILABLE
        context['STATUS_MAINTENANCE'] = constants.LOAN_STATUS_MAINTENANCE
        context['status_labels'] = dict(constants.LOAN_STATUS)
        return context


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = constants.LOAN_BOOKS_BY_USER_LIST_VIEW_PAGINATE

    def get_queryset(self):
        return (
            BookInstance.objects
            .filter(borrower=self.request.user)
            .filter(status__exact=constants.LOAN_STATUS_ON_LOAN)
            .order_by('due_back')
        )


class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    paginate_by = constants.LOAN_BOOKS_BY_USER_LIST_VIEW_PAGINATE

    def get_queryset(self):
        return (
            BookInstance.objects
            .filter(status__exact=constants.LOAN_STATUS_ON_LOAN)
            .order_by('due_back')
        )


@permission_required('catalog.can_mark_returned')
def mark_book_returned(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    book_instance.status = constants.LOAN_STATUS_AVAILABLE
    book_instance.save()
    return redirect('my-borrowed')


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':
        form = RenewBookForm(request.POST)

        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            return HttpResponseRedirect(reverse('all-borrowed'))
    else:
        proposed_renewal_date = datetime.date.today(
        ) + datetime.timedelta(weeks=constants.PROPOSED_RENEWAL_WEEKS)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = constants.BOOK_LIST_VIEW_PAGINATE


class AuthorDetailView(generic.DetailView):
    model = Author


class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': '11/06/2020'}
    template_name = 'catalog/author_form.html'


class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    template_name = 'catalog/author_confirm_delete.html'

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
  <h1>{% trans "Delete Author" %}</h1>

  <p>
    {% blocktrans with author_name=author %}
      Are you sure you want to delete the author: {{ author_name }}?
    {% endblocktrans %}
  </p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="{% trans 'Yes, delete.' %}">
  </form>
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{{ author.first_name }} {{ author.last_name }}</h1>
    <p>{% trans "Date of birth" %}: {{ author.date_of_birth }}</p>
    <p>{% trans "Date of death" %}: {{ author.date_of_death }}</p>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table> {{ form.as_table }} </table>
    <input type="submit" value="{% trans 'Submit' %}">
  </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Author List" %}</h1>
    <ul>
        {% for author in author_list %}
        <li>{{ author.last_name }}, {{ author.first_name }}</li>
        {% endfor %}
    </ul>

    {% if is_paginated %}
        <div class="pagination">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">{% trans "Previous" %}</a>
        {% endif %}

        <span>{% blocktrans with current=page_obj.number total=page_obj.paginator.num_pages %}Page {{ current }} of {{ total }}{% endblocktrans %}</span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a>
        {% endif %}
        </div>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load static %}

{% block content %}
  <h1>{% trans "Title" %}: {{ book.title }}</h1>

  <p><strong>{% trans "Author" %}:</strong> <a href="">{{ book.author }}</a></p>
  <p><strong>{% trans "Summary:" %}</strong> {{ book.summary }}</p>
  <p><strong>{% trans "ISBN:" %}</strong> {{ book.isbn }}</p>
  <p><strong>{% trans "Language" %}:</strong> {{ book.language }}</p>
  <p><strong>{% trans "Genre" %}:</strong> {{ book.genre.all|join:", " }}</p>

  <div class="book-detail-container">
    <h4>{% trans "Copies" %}</h4>
    {% for copy in copies %}
      <hr>
      <p class="{% if copy.status == STATUS_AVAILABLE %}text-success
                {% elif copy.status == STATUS_MAINTENANCE %}text-danger
                {% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != STATUS_AVAILABLE %}
        <p><strong>{% trans "Due to be returned" %}:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>{% trans "Imprint" %}:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>{% trans "ID" %}:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>

  {% if book_list %}
    <ul>
      {% for book in book_list %}
        <li>
          <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Renew" %}: {{ book_instance.book.title }}</h1>
    <p>{% trans "Borrower" %}: {{ book_instance.borrower }}</p>
    <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>
        {% trans "Due date" %}: {{ book_instance.due_back }}
    </p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="{% trans 'Submit' %}">
    </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
  <h1>{% trans "All borrowed books" %}</h1>

  {% if bookinstance_list %}
    <ul>
      {% for bookinst in bookinstance_list %}
        <li{% if bookinst.is_overdue %} class="text-danger"{% endif %}>
          <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a>
          {% blocktrans with borrower=bookinst.borrower due=bookinst.due_back %}
            - {{ borrower }} ({{ due }})
          {% endblocktrans %}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>{% trans "There are no borrowed books." %}</p>
  {% endif %}
{% endblock %}


catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}
{% load i18n %}
{% block content %}
  <h1>{% trans "Borrowed books" %}</h1>

  {% if bookinstance_list %}
    <ul>
      {% for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
          <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a>
          {% blocktrans with due=bookinst.due_back %}
            ({{ due }})
          {% endblocktrans %}

          {% if perms.catalog.can_mark_returned %}
            | <a href="{% url 'mark-returned' bookinst.pk %}">{% trans "Mark as returned" %}</a>
            | <a href="{% url 'renew-book-librarian' bookinst.pk %}">{% trans "Renew" %}</a>
          {% endif %}
        </li>
      {% empty %}
        <li>{% trans "No borrowed books." %}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>{% trans "There are no books borrowed." %}</p>
  {% endif %}
{% endblock %}
